//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace V6ThuePostXmlApi.AttachmentService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AttachmentServiceSoap", Namespace="http://tempuri.org/")]
    public partial class AttachmentService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback downloadInvAttachmentFkeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback uploadInvAttachmentFkeyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AttachmentService() {
            this.Url = global::V6ThuePostXmlApi.Properties.Settings.Default.V6ThuePostXmlApi_V6ThuePostXmlApiS_AttachmentService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AttachmentService(string url) {
            this.Url = url;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event downloadInvAttachmentFkeyCompletedEventHandler downloadInvAttachmentFkeyCompleted;
        
        /// <remarks/>
        public event uploadInvAttachmentFkeyCompletedEventHandler uploadInvAttachmentFkeyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/downloadInvAttachmentFkey", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string downloadInvAttachmentFkey(string fkey, string userName, string userPass) {
            object[] results = this.Invoke("downloadInvAttachmentFkey", new object[] {
                        fkey,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void downloadInvAttachmentFkeyAsync(string fkey, string userName, string userPass) {
            this.downloadInvAttachmentFkeyAsync(fkey, userName, userPass, null);
        }
        
        /// <remarks/>
        public void downloadInvAttachmentFkeyAsync(string fkey, string userName, string userPass, object userState) {
            if ((this.downloadInvAttachmentFkeyOperationCompleted == null)) {
                this.downloadInvAttachmentFkeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OndownloadInvAttachmentFkeyOperationCompleted);
            }
            this.InvokeAsync("downloadInvAttachmentFkey", new object[] {
                        fkey,
                        userName,
                        userPass}, this.downloadInvAttachmentFkeyOperationCompleted, userState);
        }
        
        private void OndownloadInvAttachmentFkeyOperationCompleted(object arg) {
            if ((this.downloadInvAttachmentFkeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.downloadInvAttachmentFkeyCompleted(this, new downloadInvAttachmentFkeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/uploadInvAttachmentFkey", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string uploadInvAttachmentFkey(string fkey, string userName, string userPass, string Attachment, string AttachmentExt, string AttachmentName) {
            object[] results = this.Invoke("uploadInvAttachmentFkey", new object[] {
                        fkey,
                        userName,
                        userPass,
                        Attachment,
                        AttachmentExt,
                        AttachmentName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void uploadInvAttachmentFkeyAsync(string fkey, string userName, string userPass, string Attachment, string AttachmentExt, string AttachmentName) {
            this.uploadInvAttachmentFkeyAsync(fkey, userName, userPass, Attachment, AttachmentExt, AttachmentName, null);
        }
        
        /// <remarks/>
        public void uploadInvAttachmentFkeyAsync(string fkey, string userName, string userPass, string Attachment, string AttachmentExt, string AttachmentName, object userState) {
            if ((this.uploadInvAttachmentFkeyOperationCompleted == null)) {
                this.uploadInvAttachmentFkeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadInvAttachmentFkeyOperationCompleted);
            }
            this.InvokeAsync("uploadInvAttachmentFkey", new object[] {
                        fkey,
                        userName,
                        userPass,
                        Attachment,
                        AttachmentExt,
                        AttachmentName}, this.uploadInvAttachmentFkeyOperationCompleted, userState);
        }
        
        private void OnuploadInvAttachmentFkeyOperationCompleted(object arg) {
            if ((this.uploadInvAttachmentFkeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uploadInvAttachmentFkeyCompleted(this, new uploadInvAttachmentFkeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void downloadInvAttachmentFkeyCompletedEventHandler(object sender, downloadInvAttachmentFkeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class downloadInvAttachmentFkeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal downloadInvAttachmentFkeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void uploadInvAttachmentFkeyCompletedEventHandler(object sender, uploadInvAttachmentFkeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uploadInvAttachmentFkeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uploadInvAttachmentFkeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591