
echo "--[Create database]--"
sqlcmd -E -S . -i "Structure/V6Accounting.Database.sql"

echo "--[Create roles]--]"
sqlcmd -E -S . -i "Structure/db_v6admin.Role.sql"
sqlcmd -E -S . -i "Structure/db_v6junior.Role.sql"
sqlcmd -E -S . -i "Structure/db_v6senior.Role.sql"

echo "--[Create schemas]--"
sqlcmd -E -S . -i "Structure/v6soft/Schema.sql"
sqlcmd -E -S . -i "Structure/v6sys/Schema.sql"

echo "--[Create tables]--"
sqlcmd -E -S . -i "Structure/v6soft/ModelDefinitions.Table.sql"
sqlcmd -E -S . -i "Structure/v6soft/Menu.Table.sql"
sqlcmd -E -S . -i "Structure/v6soft/alTinh.Table.sql"
sqlcmd -E -S . -i "Structure/v6soft/alQuan.Table.sql"
sqlcmd -E -S . -i "Structure/v6soft/alPhuong.Table.sql"
sqlcmd -E -S . -i "Structure/v6soft/alHinhThucThanhToan.Table.sql"
sqlcmd -E -S . -i "Structure/v6soft/alNhanVien.Table.sql"
sqlcmd -E -S . -i "Structure/v6soft/alKhachHang.Table.sql"
sqlcmd -E -S . -i "Structure/v6soft/alNhomKhachHang.Table.sql"
sqlcmd -E -S . -i "Structure/v6soft/alNhomNhanVien.Table.sql"
sqlcmd -E -S . -i "Structure/v6soft/PhanLoaiKhachHang.Table.sql"
sqlcmd -E -S . -i "Structure/v6soft/PhanLoaiNhanVien.Table.sql"

echo "--[Create procedures]--"
sqlcmd -E -S . -i "Stored procedures/v6soft/GenerateModelDefinition.Proc.sql"
sqlcmd -E -S . -i "Stored procedures/v6soft/GetModelDefinitions.Proc.sql"
sqlcmd -E -S . -i "Stored procedures/v6soft/GetModelNames.Proc.sql"
sqlcmd -E -S . -i "Stored procedures/v6soft/GetMenuItems.Proc.sql"
sqlcmd -E -S . -i "Stored procedures/v6soft/GetMenuChildren.Proc.sql"

echo "--[Insert data]--"
sqlcmd -E -S . -i "Data/v6soft/ModelDefinitions.Data.sql"
sqlcmd -E -S . -i "Data/v6soft/Menu.Data.sql"
sqlcmd -E -S . -i "Data/v6soft/alTinh.Data.sql"
sqlcmd -E -S . -i "Data/v6soft/alQuan.Data.sql"
sqlcmd -E -S . -i "Data/v6soft/alPhuong.Data.sql"
sqlcmd -E -S . -i "Data/v6soft/alHinhThucThanhToan.Data.sql"
sqlcmd -E -S . -i "Data/v6soft/alNhanVien.Data.sql"
sqlcmd -E -S . -i "Data/v6soft/alKhachHang.Data.sql"
sqlcmd -E -S . -i "Data/v6soft/alNhomKhachHang.Data.sql"
sqlcmd -E -S . -i "Data/v6soft/alNhomNhanVien.Data.sql"
sqlcmd -E -S . -i "Data/v6soft/PhanLoaiKhachHang.Data.sql"
sqlcmd -E -S . -i "Data/v6soft/PhanLoaiNhanVien.Data.sql"
pause