//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V6Soft.ServiceClients.Accounting.Customer.CustomerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RuntimeModelDC", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.OperationFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.ConstraintViolationFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<V6Soft.ServiceClients.Accounting.Customer.CustomerService.DynamicModelDC>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.DynamicModelDC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<V6Soft.Services.Common.Constants.ErrorCode>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(V6Soft.Services.Common.Constants.ErrorCode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<V6Soft.Models.Core.Constants.DefinitionIndex.Model>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(V6Soft.Models.Core.Constants.DefinitionIndex.Model))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<V6Soft.Common.ModelFactory.SearchCriterion>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(V6Soft.Common.ModelFactory.SearchCriterion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(V6Soft.Common.ModelFactory.CompareOperator))]
    public partial class RuntimeModelDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<object> FieldsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<object> Fields {
            get {
                return this.FieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldsField, value) != true)) {
                    this.FieldsField = value;
                    this.RaisePropertyChanged("Fields");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.ConstraintViolationFault))]
    public partial class OperationFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<V6Soft.Services.Common.Constants.ErrorCode> ErrorCodesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<V6Soft.Services.Common.Constants.ErrorCode> ErrorCodes {
            get {
                return this.ErrorCodesField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodesField, value) != true)) {
                    this.ErrorCodesField = value;
                    this.RaisePropertyChanged("ErrorCodes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConstraintViolationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
    [System.SerializableAttribute()]
    public partial class ConstraintViolationFault : V6Soft.ServiceClients.Accounting.Customer.CustomerService.OperationFault {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<V6Soft.Models.Core.Constants.DefinitionIndex.Model> ModelIndesesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<V6Soft.Models.Core.Constants.DefinitionIndex.Model> ModelIndeses {
            get {
                return this.ModelIndesesField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelIndesesField, value) != true)) {
                    this.ModelIndesesField = value;
                    this.RaisePropertyChanged("ModelIndeses");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DynamicModelDC", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
    [System.SerializableAttribute()]
    public partial class DynamicModelDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, object> FieldsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, object> Fields {
            get {
                return this.FieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldsField, value) != true)) {
                    this.FieldsField = value;
                    this.RaisePropertyChanged("Fields");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerService.ICustomerService")]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/AddCustomerGroup", ReplyAction="http://tempuri.org/ICustomerService/AddCustomerGroupResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.OperationFault), Action="http://tempuri.org/ICustomerService/AddCustomerGroupOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.ConstraintViolationFault), Action="http://tempuri.org/ICustomerService/AddCustomerGroupConstraintViolationFaultFault" +
            "", Name="ConstraintViolationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        V6Soft.ServiceClients.Accounting.Customer.CustomerService.AddModelResponse AddCustomerGroup(V6Soft.ServiceClients.Accounting.Customer.CustomerService.AddModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/AddCustomerGroup", ReplyAction="http://tempuri.org/ICustomerService/AddCustomerGroupResponse")]
        System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.AddModelResponse> AddCustomerGroupAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.AddModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/AddCustomer", ReplyAction="http://tempuri.org/ICustomerService/AddCustomerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.OperationFault), Action="http://tempuri.org/ICustomerService/AddCustomerOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.ConstraintViolationFault), Action="http://tempuri.org/ICustomerService/AddCustomerConstraintViolationFaultFault", Name="ConstraintViolationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        V6Soft.ServiceClients.Accounting.Customer.CustomerService.AddModelResponse AddCustomer(V6Soft.ServiceClients.Accounting.Customer.CustomerService.AddModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/AddCustomer", ReplyAction="http://tempuri.org/ICustomerService/AddCustomerResponse")]
        System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.AddModelResponse> AddCustomerAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.AddModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/AddModelItem", ReplyAction="http://tempuri.org/ICustomerService/AddModelItemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.OperationFault), Action="http://tempuri.org/ICustomerService/AddModelItemOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.ConstraintViolationFault), Action="http://tempuri.org/ICustomerService/AddModelItemConstraintViolationFaultFault", Name="ConstraintViolationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        V6Soft.ServiceClients.Accounting.Customer.CustomerService.AddModelResponse AddModelItem(V6Soft.ServiceClients.Accounting.Customer.CustomerService.AddModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/AddModelItem", ReplyAction="http://tempuri.org/ICustomerService/AddModelItemResponse")]
        System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.AddModelResponse> AddModelItemAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.AddModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/ModifyCustomerGroup", ReplyAction="http://tempuri.org/ICustomerService/ModifyCustomerGroupResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.ConstraintViolationFault), Action="http://tempuri.org/ICustomerService/ModifyCustomerGroupConstraintViolationFaultFa" +
            "ult", Name="ConstraintViolationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.OperationFault), Action="http://tempuri.org/ICustomerService/ModifyCustomerGroupOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        V6Soft.ServiceClients.Accounting.Customer.CustomerService.ModifyModelResponse ModifyCustomerGroup(V6Soft.ServiceClients.Accounting.Customer.CustomerService.ModifyModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/ModifyCustomerGroup", ReplyAction="http://tempuri.org/ICustomerService/ModifyCustomerGroupResponse")]
        System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.ModifyModelResponse> ModifyCustomerGroupAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.ModifyModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/ModifyCustomer", ReplyAction="http://tempuri.org/ICustomerService/ModifyCustomerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.OperationFault), Action="http://tempuri.org/ICustomerService/ModifyCustomerOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.ConstraintViolationFault), Action="http://tempuri.org/ICustomerService/ModifyCustomerConstraintViolationFaultFault", Name="ConstraintViolationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        V6Soft.ServiceClients.Accounting.Customer.CustomerService.ModifyModelResponse ModifyCustomer(V6Soft.ServiceClients.Accounting.Customer.CustomerService.ModifyModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/ModifyCustomer", ReplyAction="http://tempuri.org/ICustomerService/ModifyCustomerResponse")]
        System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.ModifyModelResponse> ModifyCustomerAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.ModifyModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/ModifyModelItem", ReplyAction="http://tempuri.org/ICustomerService/ModifyModelItemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.ConstraintViolationFault), Action="http://tempuri.org/ICustomerService/ModifyModelItemConstraintViolationFaultFault", Name="ConstraintViolationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.OperationFault), Action="http://tempuri.org/ICustomerService/ModifyModelItemOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        V6Soft.ServiceClients.Accounting.Customer.CustomerService.ModifyModelResponse ModifyModelItem(V6Soft.ServiceClients.Accounting.Customer.CustomerService.ModifyModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/ModifyModelItem", ReplyAction="http://tempuri.org/ICustomerService/ModifyModelItemResponse")]
        System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.ModifyModelResponse> ModifyModelItemAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.ModifyModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/RemoveCustomerGroup", ReplyAction="http://tempuri.org/ICustomerService/RemoveCustomerGroupResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.OperationFault), Action="http://tempuri.org/ICustomerService/RemoveCustomerGroupOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelResponse RemoveCustomerGroup(V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/RemoveCustomerGroup", ReplyAction="http://tempuri.org/ICustomerService/RemoveCustomerGroupResponse")]
        System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelResponse> RemoveCustomerGroupAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/RemoveCustomer", ReplyAction="http://tempuri.org/ICustomerService/RemoveCustomerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.OperationFault), Action="http://tempuri.org/ICustomerService/RemoveCustomerOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelResponse RemoveCustomer(V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/RemoveCustomer", ReplyAction="http://tempuri.org/ICustomerService/RemoveCustomerResponse")]
        System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelResponse> RemoveCustomerAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/RemoveModelItem", ReplyAction="http://tempuri.org/ICustomerService/RemoveModelItemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.OperationFault), Action="http://tempuri.org/ICustomerService/RemoveModelItemOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelResponse RemoveModelItem(V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/RemoveModelItem", ReplyAction="http://tempuri.org/ICustomerService/RemoveModelItemResponse")]
        System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelResponse> RemoveModelItemAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/TrashCustomerGroup", ReplyAction="http://tempuri.org/ICustomerService/TrashCustomerGroupResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.OperationFault), Action="http://tempuri.org/ICustomerService/TrashCustomerGroupOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelResponse TrashCustomerGroup(V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/TrashCustomerGroup", ReplyAction="http://tempuri.org/ICustomerService/TrashCustomerGroupResponse")]
        System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelResponse> TrashCustomerGroupAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/TrashCustomer", ReplyAction="http://tempuri.org/ICustomerService/TrashCustomerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.OperationFault), Action="http://tempuri.org/ICustomerService/TrashCustomerOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelResponse TrashCustomer(V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/TrashCustomer", ReplyAction="http://tempuri.org/ICustomerService/TrashCustomerResponse")]
        System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelResponse> TrashCustomerAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/TrashModelItem", ReplyAction="http://tempuri.org/ICustomerService/TrashModelItemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.OperationFault), Action="http://tempuri.org/ICustomerService/TrashModelItemOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelResponse TrashModelItem(V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/TrashModelItem", ReplyAction="http://tempuri.org/ICustomerService/TrashModelItemResponse")]
        System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelResponse> TrashModelItemAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomerGroups", ReplyAction="http://tempuri.org/ICustomerService/GetCustomerGroupsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.OperationFault), Action="http://tempuri.org/ICustomerService/GetCustomerGroupsOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse GetCustomerGroups(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomerGroups", ReplyAction="http://tempuri.org/ICustomerService/GetCustomerGroupsResponse")]
        System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse> GetCustomerGroupsAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomers", ReplyAction="http://tempuri.org/ICustomerService/GetCustomersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.OperationFault), Action="http://tempuri.org/ICustomerService/GetCustomersOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse GetCustomers(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomers", ReplyAction="http://tempuri.org/ICustomerService/GetCustomersResponse")]
        System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse> GetCustomersAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetModelItems", ReplyAction="http://tempuri.org/ICustomerService/GetModelItemsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.OperationFault), Action="http://tempuri.org/ICustomerService/GetModelItemsOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse GetModelItems(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetModelItems", ReplyAction="http://tempuri.org/ICustomerService/GetModelItemsResponse")]
        System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse> GetModelItemsAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomerGroup_ByUID", ReplyAction="http://tempuri.org/ICustomerService/GetCustomerGroup_ByUIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.OperationFault), Action="http://tempuri.org/ICustomerService/GetCustomerGroup_ByUIDOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse GetCustomerGroup_ByUID(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomerGroup_ByUID", ReplyAction="http://tempuri.org/ICustomerService/GetCustomerGroup_ByUIDResponse")]
        System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse> GetCustomerGroup_ByUIDAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomer_ByUID", ReplyAction="http://tempuri.org/ICustomerService/GetCustomer_ByUIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.OperationFault), Action="http://tempuri.org/ICustomerService/GetCustomer_ByUIDOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse GetCustomer_ByUID(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomer_ByUID", ReplyAction="http://tempuri.org/ICustomerService/GetCustomer_ByUIDResponse")]
        System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse> GetCustomer_ByUIDAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetModelItem_ByUID", ReplyAction="http://tempuri.org/ICustomerService/GetModelItem_ByUIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.OperationFault), Action="http://tempuri.org/ICustomerService/GetModelItem_ByUIDOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse GetModelItem_ByUID(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetModelItem_ByUID", ReplyAction="http://tempuri.org/ICustomerService/GetModelItem_ByUIDResponse")]
        System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse> GetModelItem_ByUIDAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomerGroup_ByCode", ReplyAction="http://tempuri.org/ICustomerService/GetCustomerGroup_ByCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.OperationFault), Action="http://tempuri.org/ICustomerService/GetCustomerGroup_ByCodeOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse GetCustomerGroup_ByCode(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomerGroup_ByCode", ReplyAction="http://tempuri.org/ICustomerService/GetCustomerGroup_ByCodeResponse")]
        System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse> GetCustomerGroup_ByCodeAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomer_ByCode", ReplyAction="http://tempuri.org/ICustomerService/GetCustomer_ByCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.OperationFault), Action="http://tempuri.org/ICustomerService/GetCustomer_ByCodeOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse GetCustomer_ByCode(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomer_ByCode", ReplyAction="http://tempuri.org/ICustomerService/GetCustomer_ByCodeResponse")]
        System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse> GetCustomer_ByCodeAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetModelItem_ByCode", ReplyAction="http://tempuri.org/ICustomerService/GetModelItem_ByCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.CustomerService.OperationFault), Action="http://tempuri.org/ICustomerService/GetModelItem_ByCodeOperationFaultFault", Name="OperationFault", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
        V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse GetModelItem_ByCode(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetModelItem_ByCode", ReplyAction="http://tempuri.org/ICustomerService/GetModelItem_ByCodeResponse")]
        System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse> GetModelItem_ByCodeAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddModelRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddModelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ushort ModelIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public V6Soft.ServiceClients.Accounting.Customer.CustomerService.RuntimeModelDC RuntimeModel;
        
        public AddModelRequest() {
        }
        
        public AddModelRequest(ushort ModelIndex, V6Soft.ServiceClients.Accounting.Customer.CustomerService.RuntimeModelDC RuntimeModel) {
            this.ModelIndex = ModelIndex;
            this.RuntimeModel = RuntimeModel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddModelResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddModelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid NewUID;
        
        public AddModelResponse() {
        }
        
        public AddModelResponse(System.Guid NewUID) {
            this.NewUID = NewUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifyModelRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ModifyModelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ushort ModelIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public V6Soft.ServiceClients.Accounting.Customer.CustomerService.RuntimeModelDC RuntimeModel;
        
        public ModifyModelRequest() {
        }
        
        public ModifyModelRequest(ushort ModelIndex, V6Soft.ServiceClients.Accounting.Customer.CustomerService.RuntimeModelDC RuntimeModel) {
            this.ModelIndex = ModelIndex;
            this.RuntimeModel = RuntimeModel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifyModelResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ModifyModelResponse {
        
        public ModifyModelResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveModelRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveModelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ushort ModelIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Guid UID;
        
        public RemoveModelRequest() {
        }
        
        public RemoveModelRequest(ushort ModelIndex, System.Guid UID) {
            this.ModelIndex = ModelIndex;
            this.UID = UID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveModelResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveModelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Success;
        
        public RemoveModelResponse() {
        }
        
        public RemoveModelResponse(bool Success) {
            this.Success = Success;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetModelsRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetModelsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Collections.Generic.List<V6Soft.Common.ModelFactory.SearchCriterion> Criteria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public ushort ModelIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Collections.Generic.List<string> OutputFields;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public ushort PageIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public ushort PageSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public System.Guid UID;
        
        public GetModelsRequest() {
        }
        
        public GetModelsRequest(string Code, System.Collections.Generic.List<V6Soft.Common.ModelFactory.SearchCriterion> Criteria, ushort ModelIndex, System.Collections.Generic.List<string> OutputFields, ushort PageIndex, ushort PageSize, System.Guid UID) {
            this.Code = Code;
            this.Criteria = Criteria;
            this.ModelIndex = ModelIndex;
            this.OutputFields = OutputFields;
            this.PageIndex = PageIndex;
            this.PageSize = PageSize;
            this.UID = UID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetModelsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetModelsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<V6Soft.ServiceClients.Accounting.Customer.CustomerService.DynamicModelDC> DynamicModels;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ulong Total;
        
        public GetModelsResponse() {
        }
        
        public GetModelsResponse(System.Collections.Generic.List<V6Soft.ServiceClients.Accounting.Customer.CustomerService.DynamicModelDC> DynamicModels, ulong Total) {
            this.DynamicModels = DynamicModels;
            this.Total = Total;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : V6Soft.ServiceClients.Accounting.Customer.CustomerService.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<V6Soft.ServiceClients.Accounting.Customer.CustomerService.ICustomerService>, V6Soft.ServiceClients.Accounting.Customer.CustomerService.ICustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public V6Soft.ServiceClients.Accounting.Customer.CustomerService.AddModelResponse AddCustomerGroup(V6Soft.ServiceClients.Accounting.Customer.CustomerService.AddModelRequest request) {
            return base.Channel.AddCustomerGroup(request);
        }
        
        public System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.AddModelResponse> AddCustomerGroupAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.AddModelRequest request) {
            return base.Channel.AddCustomerGroupAsync(request);
        }
        
        public V6Soft.ServiceClients.Accounting.Customer.CustomerService.AddModelResponse AddCustomer(V6Soft.ServiceClients.Accounting.Customer.CustomerService.AddModelRequest request) {
            return base.Channel.AddCustomer(request);
        }
        
        public System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.AddModelResponse> AddCustomerAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.AddModelRequest request) {
            return base.Channel.AddCustomerAsync(request);
        }
        
        public V6Soft.ServiceClients.Accounting.Customer.CustomerService.AddModelResponse AddModelItem(V6Soft.ServiceClients.Accounting.Customer.CustomerService.AddModelRequest request) {
            return base.Channel.AddModelItem(request);
        }
        
        public System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.AddModelResponse> AddModelItemAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.AddModelRequest request) {
            return base.Channel.AddModelItemAsync(request);
        }
        
        public V6Soft.ServiceClients.Accounting.Customer.CustomerService.ModifyModelResponse ModifyCustomerGroup(V6Soft.ServiceClients.Accounting.Customer.CustomerService.ModifyModelRequest request) {
            return base.Channel.ModifyCustomerGroup(request);
        }
        
        public System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.ModifyModelResponse> ModifyCustomerGroupAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.ModifyModelRequest request) {
            return base.Channel.ModifyCustomerGroupAsync(request);
        }
        
        public V6Soft.ServiceClients.Accounting.Customer.CustomerService.ModifyModelResponse ModifyCustomer(V6Soft.ServiceClients.Accounting.Customer.CustomerService.ModifyModelRequest request) {
            return base.Channel.ModifyCustomer(request);
        }
        
        public System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.ModifyModelResponse> ModifyCustomerAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.ModifyModelRequest request) {
            return base.Channel.ModifyCustomerAsync(request);
        }
        
        public V6Soft.ServiceClients.Accounting.Customer.CustomerService.ModifyModelResponse ModifyModelItem(V6Soft.ServiceClients.Accounting.Customer.CustomerService.ModifyModelRequest request) {
            return base.Channel.ModifyModelItem(request);
        }
        
        public System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.ModifyModelResponse> ModifyModelItemAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.ModifyModelRequest request) {
            return base.Channel.ModifyModelItemAsync(request);
        }
        
        public V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelResponse RemoveCustomerGroup(V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelRequest request) {
            return base.Channel.RemoveCustomerGroup(request);
        }
        
        public System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelResponse> RemoveCustomerGroupAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelRequest request) {
            return base.Channel.RemoveCustomerGroupAsync(request);
        }
        
        public V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelResponse RemoveCustomer(V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelRequest request) {
            return base.Channel.RemoveCustomer(request);
        }
        
        public System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelResponse> RemoveCustomerAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelRequest request) {
            return base.Channel.RemoveCustomerAsync(request);
        }
        
        public V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelResponse RemoveModelItem(V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelRequest request) {
            return base.Channel.RemoveModelItem(request);
        }
        
        public System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelResponse> RemoveModelItemAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelRequest request) {
            return base.Channel.RemoveModelItemAsync(request);
        }
        
        public V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelResponse TrashCustomerGroup(V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelRequest request) {
            return base.Channel.TrashCustomerGroup(request);
        }
        
        public System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelResponse> TrashCustomerGroupAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelRequest request) {
            return base.Channel.TrashCustomerGroupAsync(request);
        }
        
        public V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelResponse TrashCustomer(V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelRequest request) {
            return base.Channel.TrashCustomer(request);
        }
        
        public System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelResponse> TrashCustomerAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelRequest request) {
            return base.Channel.TrashCustomerAsync(request);
        }
        
        public V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelResponse TrashModelItem(V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelRequest request) {
            return base.Channel.TrashModelItem(request);
        }
        
        public System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelResponse> TrashModelItemAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.RemoveModelRequest request) {
            return base.Channel.TrashModelItemAsync(request);
        }
        
        public V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse GetCustomerGroups(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request) {
            return base.Channel.GetCustomerGroups(request);
        }
        
        public System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse> GetCustomerGroupsAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request) {
            return base.Channel.GetCustomerGroupsAsync(request);
        }
        
        public V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse GetCustomers(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request) {
            return base.Channel.GetCustomers(request);
        }
        
        public System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse> GetCustomersAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request) {
            return base.Channel.GetCustomersAsync(request);
        }
        
        public V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse GetModelItems(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request) {
            return base.Channel.GetModelItems(request);
        }
        
        public System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse> GetModelItemsAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request) {
            return base.Channel.GetModelItemsAsync(request);
        }
        
        public V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse GetCustomerGroup_ByUID(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request) {
            return base.Channel.GetCustomerGroup_ByUID(request);
        }
        
        public System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse> GetCustomerGroup_ByUIDAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request) {
            return base.Channel.GetCustomerGroup_ByUIDAsync(request);
        }
        
        public V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse GetCustomer_ByUID(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request) {
            return base.Channel.GetCustomer_ByUID(request);
        }
        
        public System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse> GetCustomer_ByUIDAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request) {
            return base.Channel.GetCustomer_ByUIDAsync(request);
        }
        
        public V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse GetModelItem_ByUID(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request) {
            return base.Channel.GetModelItem_ByUID(request);
        }
        
        public System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse> GetModelItem_ByUIDAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request) {
            return base.Channel.GetModelItem_ByUIDAsync(request);
        }
        
        public V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse GetCustomerGroup_ByCode(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request) {
            return base.Channel.GetCustomerGroup_ByCode(request);
        }
        
        public System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse> GetCustomerGroup_ByCodeAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request) {
            return base.Channel.GetCustomerGroup_ByCodeAsync(request);
        }
        
        public V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse GetCustomer_ByCode(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request) {
            return base.Channel.GetCustomer_ByCode(request);
        }
        
        public System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse> GetCustomer_ByCodeAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request) {
            return base.Channel.GetCustomer_ByCodeAsync(request);
        }
        
        public V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse GetModelItem_ByCode(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request) {
            return base.Channel.GetModelItem_ByCode(request);
        }
        
        public System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsResponse> GetModelItem_ByCodeAsync(V6Soft.ServiceClients.Accounting.Customer.CustomerService.GetModelsRequest request) {
            return base.Channel.GetModelItem_ByCodeAsync(request);
        }
    }
}
