//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V6Soft.ServiceClients.Accounting.Customer.DefinitionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModelDefinitionDC", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
    [System.SerializableAttribute()]
    public partial class ModelDefinitionDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<V6Soft.ServiceClients.Accounting.Customer.DefinitionService.ModelFieldDefinitionDC> FieldsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort IndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<V6Soft.ServiceClients.Accounting.Customer.DefinitionService.ModelFieldDefinitionDC> Fields {
            get {
                return this.FieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldsField, value) != true)) {
                    this.FieldsField = value;
                    this.RaisePropertyChanged("Fields");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort Index {
            get {
                return this.IndexField;
            }
            set {
                if ((this.IndexField.Equals(value) != true)) {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModelFieldDefinitionDC", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.DefinitionService.ModelDefinitionDC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<V6Soft.ServiceClients.Accounting.Customer.DefinitionService.ModelFieldDefinitionDC>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.DefinitionService.LengthConstraintDC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.DefinitionService.NotNullFieldConstraintDC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<V6Soft.ServiceClients.Accounting.Customer.DefinitionService.ModelDefinitionDC>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<V6Soft.ServiceClients.Accounting.Customer.DefinitionService.ModelMapDC>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(V6Soft.ServiceClients.Accounting.Customer.DefinitionService.ModelMapDC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<V6Soft.Common.ModelFactory.FieldMapping>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(V6Soft.Common.ModelFactory.FieldMapping))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(V6Soft.Common.ModelFactory.NameMapping))]
    public partial class ModelFieldDefinitionDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<object> ConstraintsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<object> Constraints {
            get {
                return this.ConstraintsField;
            }
            set {
                if ((object.ReferenceEquals(this.ConstraintsField, value) != true)) {
                    this.ConstraintsField = value;
                    this.RaisePropertyChanged("Constraints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group {
            get {
                return this.GroupField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupField, value) != true)) {
                    this.GroupField = value;
                    this.RaisePropertyChanged("Group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Label {
            get {
                return this.LabelField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelField, value) != true)) {
                    this.LabelField = value;
                    this.RaisePropertyChanged("Label");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LengthConstraintDC", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
    [System.SerializableAttribute()]
    public partial class LengthConstraintDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinLengthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxLength {
            get {
                return this.MaxLengthField;
            }
            set {
                if ((this.MaxLengthField.Equals(value) != true)) {
                    this.MaxLengthField = value;
                    this.RaisePropertyChanged("MaxLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinLength {
            get {
                return this.MinLengthField;
            }
            set {
                if ((this.MinLengthField.Equals(value) != true)) {
                    this.MinLengthField = value;
                    this.RaisePropertyChanged("MinLength");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotNullFieldConstraintDC", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
    [System.SerializableAttribute()]
    public partial class NotNullFieldConstraintDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModelMapDC", Namespace="http://schemas.datacontract.org/2004/07/V6Soft.Services.Wcf.Common.Models")]
    [System.SerializableAttribute()]
    public partial class ModelMapDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> FieldGroupsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<V6Soft.Common.ModelFactory.FieldMapping> FieldMappingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private V6Soft.Common.ModelFactory.NameMapping NameMappingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> FieldGroups {
            get {
                return this.FieldGroupsField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldGroupsField, value) != true)) {
                    this.FieldGroupsField = value;
                    this.RaisePropertyChanged("FieldGroups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<V6Soft.Common.ModelFactory.FieldMapping> FieldMappings {
            get {
                return this.FieldMappingsField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldMappingsField, value) != true)) {
                    this.FieldMappingsField = value;
                    this.RaisePropertyChanged("FieldMappings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public V6Soft.Common.ModelFactory.NameMapping NameMapping {
            get {
                return this.NameMappingField;
            }
            set {
                if ((object.ReferenceEquals(this.NameMappingField, value) != true)) {
                    this.NameMappingField = value;
                    this.RaisePropertyChanged("NameMapping");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DefinitionService.IDefinitionService")]
    public interface IDefinitionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetModelDefinition", ReplyAction="http://tempuri.org/IDefinitionService/GetModelDefinitionResponse")]
        V6Soft.ServiceClients.Accounting.Customer.DefinitionService.GetModelDefinitionsResponse GetModelDefinition(V6Soft.ServiceClients.Accounting.Customer.DefinitionService.GetModelDefinitionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetModelDefinition", ReplyAction="http://tempuri.org/IDefinitionService/GetModelDefinitionResponse")]
        System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.DefinitionService.GetModelDefinitionsResponse> GetModelDefinitionAsync(V6Soft.ServiceClients.Accounting.Customer.DefinitionService.GetModelDefinitionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetModelDefinitions", ReplyAction="http://tempuri.org/IDefinitionService/GetModelDefinitionsResponse")]
        V6Soft.ServiceClients.Accounting.Customer.DefinitionService.GetModelDefinitionsResponse GetModelDefinitions(V6Soft.ServiceClients.Accounting.Customer.DefinitionService.GetModelDefinitionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetModelDefinitions", ReplyAction="http://tempuri.org/IDefinitionService/GetModelDefinitionsResponse")]
        System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.DefinitionService.GetModelDefinitionsResponse> GetModelDefinitionsAsync(V6Soft.ServiceClients.Accounting.Customer.DefinitionService.GetModelDefinitionsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetModelDefinitionsRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetModelDefinitionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ModelName;
        
        public GetModelDefinitionsRequest() {
        }
        
        public GetModelDefinitionsRequest(string ModelName) {
            this.ModelName = ModelName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetModelDefinitionsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetModelDefinitionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public V6Soft.ServiceClients.Accounting.Customer.DefinitionService.ModelDefinitionDC ModelDefinition;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Collections.Generic.List<V6Soft.ServiceClients.Accounting.Customer.DefinitionService.ModelDefinitionDC> ModelDefinitions;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Collections.Generic.List<V6Soft.ServiceClients.Accounting.Customer.DefinitionService.ModelMapDC> ModelMaps;
        
        public GetModelDefinitionsResponse() {
        }
        
        public GetModelDefinitionsResponse(V6Soft.ServiceClients.Accounting.Customer.DefinitionService.ModelDefinitionDC ModelDefinition, System.Collections.Generic.List<V6Soft.ServiceClients.Accounting.Customer.DefinitionService.ModelDefinitionDC> ModelDefinitions, System.Collections.Generic.List<V6Soft.ServiceClients.Accounting.Customer.DefinitionService.ModelMapDC> ModelMaps) {
            this.ModelDefinition = ModelDefinition;
            this.ModelDefinitions = ModelDefinitions;
            this.ModelMaps = ModelMaps;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDefinitionServiceChannel : V6Soft.ServiceClients.Accounting.Customer.DefinitionService.IDefinitionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DefinitionServiceClient : System.ServiceModel.ClientBase<V6Soft.ServiceClients.Accounting.Customer.DefinitionService.IDefinitionService>, V6Soft.ServiceClients.Accounting.Customer.DefinitionService.IDefinitionService {
        
        public DefinitionServiceClient() {
        }
        
        public DefinitionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DefinitionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DefinitionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DefinitionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public V6Soft.ServiceClients.Accounting.Customer.DefinitionService.GetModelDefinitionsResponse GetModelDefinition(V6Soft.ServiceClients.Accounting.Customer.DefinitionService.GetModelDefinitionsRequest request) {
            return base.Channel.GetModelDefinition(request);
        }
        
        public System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.DefinitionService.GetModelDefinitionsResponse> GetModelDefinitionAsync(V6Soft.ServiceClients.Accounting.Customer.DefinitionService.GetModelDefinitionsRequest request) {
            return base.Channel.GetModelDefinitionAsync(request);
        }
        
        public V6Soft.ServiceClients.Accounting.Customer.DefinitionService.GetModelDefinitionsResponse GetModelDefinitions(V6Soft.ServiceClients.Accounting.Customer.DefinitionService.GetModelDefinitionsRequest request) {
            return base.Channel.GetModelDefinitions(request);
        }
        
        public System.Threading.Tasks.Task<V6Soft.ServiceClients.Accounting.Customer.DefinitionService.GetModelDefinitionsResponse> GetModelDefinitionsAsync(V6Soft.ServiceClients.Accounting.Customer.DefinitionService.GetModelDefinitionsRequest request) {
            return base.Channel.GetModelDefinitionsAsync(request);
        }
    }
}
