CREATE TABLE [dbo].[TBL_DETAIL] (
  [ID_MASTER] nvarchar(24) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NOT NULL,
  [STT] numeric(3)  NULL,
  [IDSTT] numeric(3) DEFAULT ((0)) NOT NULL,
  [MAHANG] nvarchar(12) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NOT NULL,
  [TENHANG] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NOT NULL,
  [DONGIA] decimal(12,2) DEFAULT ((0)) NOT NULL,
  [THUESUAT] nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NOT NULL,
  [DONVITINH] nvarchar(24) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NOT NULL,
  [SOLUONG] decimal(12,3) DEFAULT ((0)) NOT NULL,
  [THANHTIEN] decimal(12,2) DEFAULT ((0)) NOT NULL,
  [TIENTHUE] decimal(12,2) DEFAULT ((0)) NOT NULL,
  [TONGTIEN] decimal(12,2) DEFAULT ((0)) NOT NULL,
  [KHUYENMAI] decimal(12,2) DEFAULT ((0)) NOT NULL,
  [THUETTDB] nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NOT NULL,
  [TTHD_KYHIEU] nvarchar(12) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NOT NULL,
  [TTHD_SOHOADON] nvarchar(12) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NOT NULL,
  [TTHD_MAUSO] nvarchar(12) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NOT NULL,
  [TTHD_NGAYHOADON] datetime  NULL,
  [TTHD_NGAYTINHTRANGHD] datetime  NULL,
  [TINHTRANGHOADON] int DEFAULT ((0)) NOT NULL,
  [TS24NGAYCAPNHAT] datetime  NULL,
  [KHONGHIENTHI] int DEFAULT ((0)) NOT NULL,
  CONSTRAINT [PK__TB_DETAI__07CC7ABC36B12243] PRIMARY KEY CLUSTERED ([ID_MASTER])
WITH (PAD_INDEX = OFF, FILLFACTOR = 90, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)  
ON [PRIMARY]
)  
ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBL_DETAIL] SET (LOCK_ESCALATION = TABLE)
GO

CREATE NONCLUSTERED INDEX [ID_MASTER]
ON [dbo].[TBL_DETAIL] (
  [ID_MASTER] ASC
)