CREATE TABLE [dbo].[TBL_MASTER] (
  [ID_MASTER] nvarchar(24) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NOT NULL,
  [SODONHANG] nvarchar(18) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NOT NULL,
  [NGAYDONHANG] datetime  NULL,
  [MAKHACHHANG] nvarchar(12) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [TENKHACHHANG] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [TENDONVI] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [MASOTHUE] nvarchar(16) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [DIACHI] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [DIENTHOAINGUOIMUA] nvarchar(24) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [FAXNGUOIMUA] nvarchar(24) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [EMAILNGUOIMUA] nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [SOTAIKHOAN] nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [NOIMOTAIKHOAN] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [HINHTHUCTT] nvarchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [TONGTIENHANG] decimal(12,2) DEFAULT ((0)) NULL,
  [TONGTIENTHUE] decimal(12,2) DEFAULT ((0)) NULL,
  [TONGTIENCKGG] decimal(12,2) DEFAULT ((0)) NULL,
  [TIENCHIPHIKHAC] decimal(12,2) DEFAULT ((0)) NULL,
  [TONGTIENTT] decimal(12,2) DEFAULT ((0)) NULL,
  [SOTIENBANGCHU] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [MACN_CH] nvarchar(12) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [TENCN_CH] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [ID_MASTER_REF] nvarchar(24) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [THONGTINHOADON] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [KYHIEUHD] nvarchar(12) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [SOHOADON] nvarchar(12) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [MAUSOHD] nvarchar(12) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [NGAYHOADON] datetime  NULL,
  [NGAYTINHTRANGHD] datetime  NULL,
  [TINHTRANGHOADON] int DEFAULT ((0)) NULL,
  [MANHANHOADON] nvarchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [SOHIEUBANGKE] nvarchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [THONGTINCHUNGHOADON] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [SOHOPDONG] nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [NGAYHOPDONG] datetime  NULL,
  [SOVANDON] nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [SOCONTAINER] nvarchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [TINHTRANGKYNGUOIBAN] int DEFAULT ((0)) NULL,
  [NGAYKYNGUOIBAN] datetime  NULL,
  [TS24NGAYCAPNHAT] datetime  NULL,
  [NGAYTAO] datetime  NULL,
  [NGAYCAPNHATERP] datetime  NULL,
  [LOAITIENTE] nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT ('VND') NULL,
  [TYGIA] numeric(12,4) DEFAULT ((1)) NULL,
  [SOTHAMCHIEU] nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [TAIKHOANNGUOINGAN] nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [TAIKHOANGIAONHAN] nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [GHICHU] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
  [HANTHANHTOAN] datetime  NULL,
  CONSTRAINT [PK__TB_MASTE__E9A5CC1C398D8EEE] PRIMARY KEY CLUSTERED ([ID_MASTER])
WITH (PAD_INDEX = OFF, FILLFACTOR = 90, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)  
ON [PRIMARY]
)  
ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBL_MASTER] SET (LOCK_ESCALATION = TABLE)
GO

CREATE NONCLUSTERED INDEX [SDH]
ON [dbo].[TBL_MASTER] (
  [SODONHANG] ASC
)
GO

CREATE NONCLUSTERED INDEX [ID_MASTER]
ON [dbo].[TBL_MASTER] (
  [ID_MASTER] ASC
)
GO

CREATE NONCLUSTERED INDEX [SODONHANG]
ON [dbo].[TBL_MASTER] (
  [SODONHANG] ASC
)
GO

CREATE NONCLUSTERED INDEX [NGAYDONHANG]
ON [dbo].[TBL_MASTER] (
  [NGAYDONHANG] ASC
)
GO

CREATE NONCLUSTERED INDEX [MACN_CH]]]
ON [dbo].[TBL_MASTER] (
  [MACN_CH] ASC
)
GO

CREATE NONCLUSTERED INDEX [TINHTRANGHOADON]
ON [dbo].[TBL_MASTER] (
  [TINHTRANGHOADON] ASC
)