//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V6ThuePostXmlApi.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://0315511086-democadmin.vnpt-invoice.com.vn/PublishService.asmx")]
        public string V6ThuePostXmlApi_PublishService0315511086_PublishService {
            get {
                return ((string)(this["V6ThuePostXmlApi_PublishService0315511086_PublishService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://0315511086-democadmin.vnpt-invoice.com.vn/PortalService.asmx")]
        public string V6ThuePostXmlApi_PortalService0315511086_PortalService {
            get {
                return ((string)(this["V6ThuePostXmlApi_PortalService0315511086_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://0315511086-democadmin.vnpt-invoice.com.vn/BusinessService.asmx")]
        public string V6ThuePostXmlApi_BusinessService0315511086_BusinessService {
            get {
                return ((string)(this["V6ThuePostXmlApi_BusinessService0315511086_BusinessService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://0315511086-democadmin.vnpt-invoice.com.vn/AttachmentService.asmx")]
        public string V6ThuePostXmlApi_AttachmentService0315511086_AttachmentService {
            get {
                return ((string)(this["V6ThuePostXmlApi_AttachmentService0315511086_AttachmentService"]));
            }
        }
    }
}
